# Generated by Django 5.0.12 on 2025-02-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.menudiario')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.plato')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_promocional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.plato')),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurante')),
            ],
        ),
    ]
