# Generated by Django 5.0.12 on 2025-03-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_promocional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.menudiario')),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurante')),
            ],
        )
    ]
