# Generated by Django 5.0.12 on 2025-02-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='authentication.usuario')),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.plato')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateField()),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.plato')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateField()),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurante')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario')),
            ],
        ),
    ]
